version: "3"
services:
  hub:
    image: selenium/hub:4.3.0
    ports:
      - "4442:4442"
      - "4443:4443"
      - "4444:4444"

  chrome:
    image: selenium/node-chrome:4.3.0
    shm_size: '3gb'
    depends_on:
      - hub
    links:
      - hub
    environment:
      - SE_EVENT_BUS_HOST=hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
      - SCREEN_WIDTH=1920
      - SCREEN_HEIGHT=1080
      - VNC_NO_PASSWORD=1

  test-run:
    build: .
    container_name: test-run
    depends_on:
      - chrome
    links:
      - hub
    environment:
      - HRM_USERNAME=${HRM_USERNAME}
      - HRM_PASSWORD=${HRM_PASSWORD}
      - HUB_HOST=hub
      - MODULE=testng.xml
    volumes:
      - ./src/test/resources/results:/app
      - ./allure-results:/app